stages:
  - testing
  - build

run_tests:
  image: denoland/deno:latest
  stage: testing
  script:
    - deno test

build_docker_image:
  stage: build
  needs:
    - run_tests
  script:
    - docker build -t shopping-cat .